### ISSUE TITLE
Default template still requires livereload ~> 3.1.0

### ISSUE THREAD

**Issue by komor72** [middleman/middleman-templates-default#1]
The default template as of Middleman 3.3.6 still requires old version of livereload:

```
gem "middleman-livereload", "~> 3.1.0"
```

Current version of [https://github.com/middleman/middleman-livereload](middleman-livereload) is 3.3.4 (3.3.0 in changelog documented). Is this correct?

**Comment by tysongach** [comment]
Apologies for not getting a response, but this is now out of date and not a current issue.
