### ISSUE TITLE
Remove lagacy sprockets pragma

### ISSUE THREAD

**Issue by zuf** [middleman/middleman-templates-default#5]
Unused sprockets directive still presents by default:

https://github.com/middleman/middleman-templates-default/blob/8a16e7cb8a491505124d6e47649ddba04d65203c/template/source/javascripts/all.js#L1

**Comment by tysongach** [comment]
This was removed in https://github.com/middleman/middleman-templates-default/commit/543f41c7f9a0e7a2d07365c8daee7aee69a6968f.
